/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MockDataRouteImport } from './routes/mock-data'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockDataRoute = MockDataRouteImport.update({
  id: '/mock-data',
  path: '/mock-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mock-data': typeof MockDataRoute
  '/api/generate': typeof ApiGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mock-data': typeof MockDataRoute
  '/api/generate': typeof ApiGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mock-data': typeof MockDataRoute
  '/api/generate': typeof ApiGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mock-data' | '/api/generate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mock-data' | '/api/generate'
  id: '__root__' | '/' | '/mock-data' | '/api/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MockDataRoute: typeof MockDataRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-data': {
      id: '/mock-data'
      path: '/mock-data'
      fullPath: '/mock-data'
      preLoaderRoute: typeof MockDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MockDataRoute: MockDataRoute,
  ApiGenerateRoute: ApiGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
